services:
  backend:
    image: aliulislamabir/oracle-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - oracle-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge